export const GET_NEXT_PAGE = 'GET_NEXT_PAGE'
export const GET_PREVIOUS_PAGE = 'GET_PREVIOUS_PAGE'
export const SELECT_ANSWER_YOU = 'SELECT_ANSWER_YOU'
export const SELECT_ANSWER_PARTNER = 'SELECT_ANSWER_PARTNER'